### ISSUE TITLE
Error: 'More' box gone awry

### ISSUE THREAD

**Issue by SpoffSpiff** [erkyrath/quixe#10]
In the current version of Firefox (41.0) and Internet Explorer, the lower-right 'More' box sometimes shows up for no reason, and pressing space seldom make it go away. The Chrome browser doesn't feature this bug.s

I don't think it happen in all games, though. I have noticed the bug in those games:
http://eblong.com/zarf/glulx/quixe/quixe/play-remote.html?story=stories/Reliques.gblorb.js
http://eblong.com/zarf/glulx/quixe/quixe/play-remote.html?story=stories/Advent.ulx.js
http://eblong.com/zarf/glulx/quixe/quixe/play-remote-onecol.html?story=stories/Advent.ulx.js

But not here: (maybe due to its classic layout?)
http://eblong.com/zarf/glulx/quixe/i7-release/play.html

The bug isn't very reliable - sometimes, the games run fine.

**Comment by erkyrath** [comment]
Zooming in seems relevant. See related bug.

**Comment by erkyrath** [comment]
Turned out to be a rounding error -- the scroll position would get within 0.25 or so of "the bottom", but not exactly there. Add a couple of pixels of margin-of-error and the problem goes away.
