### ISSUE TITLE
I7's "release along with an interpreter" feature shows no graphics in Counterfeit Monkey

### ISSUE THREAD

**Issue by angstsmurf** [erkyrath/quixe#26]
It was pointed out to me that if you add "Release along with an interpreter" to the source, the resulting play-in-browser page will only show a black square where the map should be. I'm not sure if this is even supposed to work.

**Comment by erkyrath** [comment]
This is not supposed to work. The Inform compiler does not include the images in the "interpreter" directory in any form. (The file "Counterfeit Monkey.gblorb.js" is not actually a blorb file and contains no image data.)

Getting this to work requires an I7 update, which is covered at https://inform7.uservoice.com/forums/57320-general/suggestions/12890385-fully-support-sound-and-image-resources-in-quixe .

**Comment by curiousdannii** [comment]
If the template was changed to load the real gblorb rather than [ENCODEDSTORYFILE], would it work?

It's been so long since we set up the JSONP system that I don't remember which browsers it was needed for and whether they are still relevant. Perhaps we can just load the normal storyfile now.

**Comment by erkyrath** [comment]
No. 

You can do a postprocessing step where you run "blorbtool.py giload" on the real gblorb file, and it writes out all the necessary data into the interpreter directory.

**Comment by curiousdannii** [comment]
What I meant is that play-remote.html will extract images from blorbs, then we might be able to make it easier to set up (even if the blorbtool giload method is better performance-wise). But it depends on the browsers and their file:// rules. Chrome was the problem last time, and probably still is.

**Comment by erkyrath** [comment]
> But if the whole blorb file is put through game2js.py then it might just work.

Yes, that works. That's one of the options I mention in the uservoice post. But if I7 needs to be updated, it might as well use the high-performance option.
