### ISSUE TITLE
Not able to play gblorb file

### ISSUE THREAD

**Issue by Baltasarq** [erkyrath/quixe#28]
The boot process stops with: "Quixe init: glk_put_jstring: invalid stream"
The gblorb file is: http://caad.es/baltasarq/if/visitantes/visitantes.gblorb [spanish IF]
I've tried converting it to JavaScript with and without --giload.

**Comment by erkyrath** [comment]
This is almost certainly a bug in the game.

**Comment by Baltasarq** [comment]
The game runs fine both in git and glulxe.

**Comment by erkyrath** [comment]
The game is writing to an invalid stream or window. Not all Glk libraries report this error, but it is an error.

**Comment by Baltasarq** [comment]
All right, so you have two choices: fix that so your interpreter is able to
play a lot of games with an unnoticed (till now) error, or be the author of
a righteous interpreter unable to play a lot of games.

-- Baltasar

**Comment by erkyrath** [comment]
I regret the current situation, but it should be fixed in the development tools.

I can only recommend you support https://inform7.uservoice.com/forums/57320-general/suggestions/1933277-the-ide-interpreter-should-reject-invalid-glk-call .

**Comment by erkyrath** [comment]
I should note that it's not just Quixe. I support several Glk libraries, and other people support yet more. Merely saying "fix my interpreter" does not solve the problem.

The choice before me are to leave the spec and say the games are wrong, or change the spec and say the interpreters are wrong. Either of them involves telling people to do work. It's not just me being lazy.

**Comment by curiousdannii** [comment]
Just to clarify a little: with this kind of error it doesn't matter if you use Git or Glulxe, what matters is the Glk implementation. If you use a lax Glk implementation (like Windows Glk I think?) then both will say nothing, but if you use a strict one then both will show the error.

@erkyrath What are some other strict Glk implementations which @Baltasarq could use to test this? Is cheapglk?

**Comment by erkyrath** [comment]
CheapGlk is strict, but this game uses graphics and multiple windows so it's never going to run under CheapGlk. (Really it should check those capabilities too, but that's a different fight.)

RemGlk is also strict, but again, it doesn't support graphics. Ask again next month.

**Comment by Baltasarq** [comment]
Interesting. Are you saying that I cannot play this game in Linux? Because I can.
It also works in Zag, a completely diferent (Java) implementation.

Alas, I have a ulx (text-only, working in all interpreters but producing the same error just in Quixe) and z5 versions, produced from the very same code base (BTW, the z5 works flawlessly in all interpreters, even Parchment). The game was developed with Inform6.

Nevermind. I'm just tired of taking the effort of reporting a bug just to find the (childish attitude, INMHO) of the author(s) defending themselves with the "it's not my fault". You have the info, do whatever you want.

**Comment by erkyrath** [comment]
The situation is frustrating for me too, but I cannot resolve it by changing one line of code or even one library.

I am hoping that with Lectrote out, authors will be able to test this case more easily.

(I am also hoping that the IDE interpreter is updated to be more strict, of course.)

**Comment by cogwheel** [comment]
I'm going to second @Baltasarq here. This seems like a case of ignoring the spirit of the spec in favor of strict adherence to its wording. The effect is that it surprises the end user, which _should_ be the target audience of a library like this.

As a player of interactive fiction, I want to be able to load a well-known game into any interpreter that claims to run these games. Quix fails to provide this for certain games, such as "Everybody dies." This game works in every other interpreter I've tried.

Most other platform developers recognize this. Operating systems, programming languages, etc. all include quirks for backwards compatibility. It's annoying, but it's the right thing to do in order to adhere to the principle of least surprise. "Everybody else is doing it wrong" may be true, but that doesn't mean this is the right way to address the issue.

**Comment by salty-horse** [comment]
I think this was finally fixed by https://github.com/erkyrath/quixe/commit/6e2fc27c438c537419c1ae24acaae8bfa7f4275b

**Comment by salty-horse** [comment]
Sorry, it is a different bug. Parchment was giving me unrelated troubles, so I couldn't verify the file at the top. But now that I check it, I see the same error.
