### ISSUE TITLE
default_story: 'stories/glulxercise.ulx',

### ISSUE THREAD

**Issue by stone1343** [erkyrath/quixe#29]
Hi, in the play-remote*.html files, I think this line:
default_story: 'stories/glulxercise.ulx',
should be changed to this:
default_story: 'stories/glulxercise.ulx.js',
so they work out of the box

Thanks, I'm making a game that will use Quixe, so I'm motivated to help

**Comment by erkyrath** [comment]
It does work out of the box -- e.g., http://eblong.com/zarf/glulx/quixe/quixe/play-remote-full.html . 

It fails when run off a file: URL in Chrome. I think Chrome's security limitations are probably correct, but running play-remote.html as distributed isn't the normal thing to do anyway -- it's really there only for testing and as a demo.
