### ISSUE TITLE
Use https proxy URL

### ISSUE THREAD

**Issue by erkyrath** [erkyrath/quixe#37]
If a game is installed on an https site using the proxy load mechanism, Chrome will throw an error because it's going through http://zcode.appspot.com/proxy/.

Change this to https://zcode.appspot.com/proxy/.

(I think this is the cause of https://github.com/erkyrath/quixe/issues/29 .)

**Comment by erkyrath** [comment]
Fixed.

In particular this was breaking my "Play it!" demo button on https://eblong.com/zarf/glulx/quixe/ .

**Comment by curiousdannii** [comment]
https://proxy.iplayif.com is another option. Doesn't make a difference though.
