### ISSUE TITLE
Add an option to disable logging

### ISSUE THREAD

**Issue by juhana** [erkyrath/quixe#39]
Currently there's no way to stop Quixe from printing `qlog` or `glkote_log` debug messages (apart from disabling console.log completely) which pollutes the console if you're using it to debug something that's not Quixe-related.

**Comment by erkyrath** [comment]
Do you need to turn off logging entirely, or are you just annoyed by the "### done executing; path time" messages? There's a limited number of startup log messages, and I don't want to disable logging of exceptions and serious errors.

**Comment by juhana** [comment]
Right, I'd prefer the option to not see info-level messages like the execution time measurements.

**Comment by erkyrath** [comment]
Okay, I've added this as game_options.log_execution_time.
