### ISSUE TITLE
Instruction Clarification?

### ISSUE THREAD

**Issue by ccfox** [erkyrath/quixe#51]
Sorry if this isn't the place to put this, but Github doesn't really allow private message or complex forum posts. I was wondering if the instructions for using this interpreter could be clarified a bit, as the problems I am running into are almost certainly due to me misreading something within them.

The instructions do not produce the desired results for me, at least the way I am following them. Using "Release along with the "Quixe" interpreter." in Inform 7 (the last beta version that doesn't turn all the important text sideways) does not release it with what is downloaded here, instead releasing it with the default interpreter released with using "Release along with an interpreter.". Further, the python script doesn't seem to be doing what its supposed to.

I download the zip file (by clicking on code>download as zip) and unzip it into Documents\Inform\Templates as instructed, and have tried multiple times to get the python script to work at all (though it sounds like the easiest method that should work is simply having Inform do the 'heavy lifting' for me.

Thanks in advance for any clarification that can be provided, and I apologise again for bothering you all about this here.

**Comment by erkyrath** [comment]
(The forum for asking Inform 7 questions is https://intfiction.org/ .)

Documents/Inform/Templates requires a particular layout, which this repo is not in. You can get the right layout by downloading https://eblong.com/zarf/glulx/quixe/Quixe-221.zip (or the latest zip file shown at https://eblong.com/zarf/glulx/quixe/) and unzipping that into the Templates directory.

**Comment by ccfox** [comment]
Apologies! I appreciate the clarification regardless, and see where I got confused now.
