### ISSUE TITLE
Saving user input and parser output on the server

### ISSUE THREAD

**Issue by IkeC** [erkyrath/quixe#53]
When hosting this on your own server, is it possible to save the user input and possibly the parser output to a file (or database) on the server?

If not, would there be a reasonable way to implement this, or are there other systems that have this that I'm not aware of? I might even have a go at implementing it myself if I get some pointers in the right direction.

**Comment by curiousdannii** [comment]
Yes, if you set these options then it will send updates to a server.
```
    /** Transcript recording service protocol format. Set to `simple`  */
    recording_format: 'simple',
    /** Transcript recording label for this story */
    recording_label: 'game name',
    /** URL for the transcript recording service */
    recording_url: 'https://server',
```

Here's a sample server along with a description of the data format.
https://github.com/curiousdannii/asyncglk/tree/master/tools/transcript-server

**Comment by IkeC** [comment]
Wow great, thanks for the quick reply!
