### ISSUE TITLE
Wrong results on address calculation overflow in aloadbit/astorebit

### ISSUE THREAD

**Issue by hanna-kruppe** [erkyrath/quixe#55]
For the `aloadbit` and `astorebit` opcodes, the calculation of which byte of memory to access may overflow. Adding a positive bit offset L2 to a very large (unsigned) base address L1 can go past 2^32 - 1, and conversely adding a negative bit offset to a very small base address can result in a negative number (or wrap around if interpreted as unsigned).

I wrote a small test program for this, see below.  Git and Glulxe wrap around in the address space, i.e., `aloadbit (-1) 9` loads bit 1 of byte address 0. Quixe always loads zeros instead. I guess that's because it doesn't coerce the calculated byte address into a 32-bit integer before passing it to `Mem1`. This results in using a byte address >= 2^32 or < 0, reading `undefined` from the memory array, and I guess `undefined` makes the rest of the opcode implementation put 0 into the destination. If there were bounds check for the memory accesses they would presumably fail, but it seems Quixe (deliberately?) doesn’t have such checks.

My test program doesn't cover `astorebit` because that's marginally harder to do properly, but from how similar the implementation is I assume it has the same underlying issue. From some quick experiments, writing to a "negative" or overly large address appears to "work" in that subsequent `aloadbit` can read the written data back, but it seems that other instructions can't. Luckily writing to a very large index in the memory array doesn't immediately allocate as much memory, at least in my browser.

I'm reporting this as a Quixe issue because I assume the Glulxe/Git wraparound behavior is the "right" one even if the spec doesn't seem to say anything about it. Wrapping around is also somewhat consistent with how all interpreters (including Quixe from what I've seen) handle address overflow in the other (non-bit) array load/store opcodes.

Test program:

```
[Main win i;
    @setiosys 2 0;
    win = glk($0023, 0, 0, 0, 3, 0); ! glk_window_open
    glk($002F, win); ! glk_set_window

    for (i = 0 : i < 32 : i++) {
        check(i, load_byte_as_8bits(-1, 8 * (i + 1)), 0->i);
    }
];

[load_byte_as_8bits byte_base bit_offset i bit result;
    result = 0;
    for (i = 0 : i < 8 : i++, bit_offset++) {
        @aloadbit byte_base bit_offset bit;
        @shiftl bit i bit;
        @bitor result bit result;
    }
    return result;
];

[check i lhs rhs;
    print "byte ", i, ": ";
    if (lhs == rhs) print lhs, " OK^";
    else print "ERROR: ", lhs, " != ", rhs, "^";
];
```

**Comment by erkyrath** [comment]
> I'm reporting this as a Quixe issue because I assume the Glulxe/Git wraparound behavior is the "right" one even if the spec doesn't seem to say anything about it. 

I'm inclined to say that the wraparound behavior is an accident of implementation. The C interpreters do their intermediate address calculations in 32-bit variables but there's no reason to mandate that.

So this is an undefined-behavior case.

> Quixe (deliberately?) doesn’t have such checks.

Memory bounds checks would slow Quixe down so I decided to skip them. (Unlike in C, overrunning the JS memory array isn't a security hole.)

**Comment by erkyrath** [comment]
I'm afraid that wraparound doesn't make sense to me. I don't believe there's any code out there that accidentally does this. 

It's true that it would be nicer if Quixe asserted on all undefined behavior, but it doesn't, and it's not reasonable to adjust the spec to match what's practical in Javascript.

**Comment by hanna-kruppe** [comment]
Fair enough. In that case I think I'll keep it a fatal error in my interpreter, where it's not a performance concern. Usually I prefer to match the behavior of the big three Glulx interpreters, or at least some of them if there's multiple reasonable options. But if it's undefined, actually different between interpreters, and probably not relied on by existing gamefiles, then there's no harm and possibly some use in reporting it as an error when easily possible.
